import type { Metadata } from "next";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { use } from "react";

const navLinks = [
  { name: "Login", href: "/auth/login" },
  { name: "Register", href: "/auth/register" },
  { name: "Forgot Password", href: "/auth/forgot-password" },
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <div>
      {navLinks.map((link) => {
        const isActive =
          pathname === link.href ||
          (pathname.startsWith(link.href) && link.href !== "/auth");
        return (
          <Link
            className={isActive ? "font-bold mr-4" : "text-blue-500"}
            href={link.href}
            key={link.name}
          >
            {link.name}
          </Link>
        );
      })}
      {children}
    </div>
  );
}
