import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
        <footer className="p-4 border-t border-gray-300 mt-8 text-center bg-amber-500">
          <p>© 2024 My Next.js App</p>
        </footer>
      </body>
    </html>
  );
}
